// Code generated by scripts/generate-cli-spec-go.mjs from
// packages/types/src/cli-api.ts. DO NOT EDIT by hand — change the TypeScript
// source of truth and regenerate instead.

package spec

// RequestFailure mirrors the RequestFailure union in packages/types/src/cli-api.ts.
type RequestFailure string

const (
	RequestFailureBadRequest  RequestFailure = "bad-request"
	RequestFailureRateLimited RequestFailure = "rate-limited"
	RequestFailureCrossOrigin RequestFailure = "cross-origin"
	RequestFailureNotSignedIn RequestFailure = "not-signed-in"
)

// RequestFailures lists every RequestFailure value, in declaration order.
var RequestFailures = []RequestFailure{
	RequestFailureBadRequest,
	RequestFailureRateLimited,
	RequestFailureCrossOrigin,
	RequestFailureNotSignedIn,
}

// StartFailure mirrors the StartFailure union in packages/types/src/cli-api.ts.
type StartFailure string

const (
	StartFailureInvalidPublicKey StartFailure = "invalid-public-key"
	StartFailureUnknownNetwork   StartFailure = "unknown-network"
	StartFailureNetworkMismatch  StartFailure = "network-mismatch"
	StartFailureUnavailable      StartFailure = "unavailable"
)

// StartFailures lists every StartFailure value, in declaration order.
var StartFailures = []StartFailure{
	StartFailureInvalidPublicKey,
	StartFailureUnknownNetwork,
	StartFailureNetworkMismatch,
	StartFailureUnavailable,
}

// PollFailure mirrors the PollFailure union in packages/types/src/cli-api.ts.
type PollFailure string

const (
	PollFailureUnavailable PollFailure = "unavailable"
	PollFailureNotFound    PollFailure = "not-found"
)

// PollFailures lists every PollFailure value, in declaration order.
var PollFailures = []PollFailure{
	PollFailureUnavailable,
	PollFailureNotFound,
}

// ApproveFailure mirrors the ApproveFailure union in packages/types/src/cli-api.ts.
type ApproveFailure string

const (
	ApproveFailureNotFound    ApproveFailure = "not-found"
	ApproveFailureExpired     ApproveFailure = "expired"
	ApproveFailureAlreadyUsed ApproveFailure = "already-used"
	ApproveFailureNoProfile   ApproveFailure = "no-profile"
	ApproveFailureNoKey       ApproveFailure = "no-key"
	ApproveFailureUnavailable ApproveFailure = "unavailable"
)

// ApproveFailures lists every ApproveFailure value, in declaration order.
var ApproveFailures = []ApproveFailure{
	ApproveFailureNotFound,
	ApproveFailureExpired,
	ApproveFailureAlreadyUsed,
	ApproveFailureNoProfile,
	ApproveFailureNoKey,
	ApproveFailureUnavailable,
}

// ApproveOutcome mirrors the ApproveOutcome union in packages/types/src/cli-api.ts.
type ApproveOutcome string

const (
	ApproveOutcomeOK          ApproveOutcome = "ok"
	ApproveOutcomeNotFound    ApproveOutcome = "not-found"
	ApproveOutcomeExpired     ApproveOutcome = "expired"
	ApproveOutcomeAlreadyUsed ApproveOutcome = "already-used"
	ApproveOutcomeNoProfile   ApproveOutcome = "no-profile"
	ApproveOutcomeNoKey       ApproveOutcome = "no-key"
	ApproveOutcomeUnavailable ApproveOutcome = "unavailable"
)

// ApproveOutcomes lists every ApproveOutcome value, in declaration order.
var ApproveOutcomes = []ApproveOutcome{
	ApproveOutcomeOK,
	ApproveOutcomeNotFound,
	ApproveOutcomeExpired,
	ApproveOutcomeAlreadyUsed,
	ApproveOutcomeNoProfile,
	ApproveOutcomeNoKey,
	ApproveOutcomeUnavailable,
}

// RejectFailure mirrors the RejectFailure union in packages/types/src/cli-api.ts.
type RejectFailure string

const (
	RejectFailureNotFound    RejectFailure = "not-found"
	RejectFailureExpired     RejectFailure = "expired"
	RejectFailureAlreadyUsed RejectFailure = "already-used"
	RejectFailureUnavailable RejectFailure = "unavailable"
)

// RejectFailures lists every RejectFailure value, in declaration order.
var RejectFailures = []RejectFailure{
	RejectFailureNotFound,
	RejectFailureExpired,
	RejectFailureAlreadyUsed,
	RejectFailureUnavailable,
}

// RejectOutcome mirrors the RejectOutcome union in packages/types/src/cli-api.ts.
type RejectOutcome string

const (
	RejectOutcomeOK          RejectOutcome = "ok"
	RejectOutcomeNotFound    RejectOutcome = "not-found"
	RejectOutcomeExpired     RejectOutcome = "expired"
	RejectOutcomeAlreadyUsed RejectOutcome = "already-used"
	RejectOutcomeUnavailable RejectOutcome = "unavailable"
)

// RejectOutcomes lists every RejectOutcome value, in declaration order.
var RejectOutcomes = []RejectOutcome{
	RejectOutcomeOK,
	RejectOutcomeNotFound,
	RejectOutcomeExpired,
	RejectOutcomeAlreadyUsed,
	RejectOutcomeUnavailable,
}

// CompleteFailure mirrors the CompleteFailure union in packages/types/src/cli-api.ts.
type CompleteFailure string

const (
	CompleteFailureUnavailable          CompleteFailure = "unavailable"
	CompleteFailureNotFound             CompleteFailure = "not-found"
	CompleteFailureExpired              CompleteFailure = "expired"
	CompleteFailureNotApproved          CompleteFailure = "not-approved"
	CompleteFailureAlreadyCompleted     CompleteFailure = "already-completed"
	CompleteFailureNetworkMismatch      CompleteFailure = "network-mismatch"
	CompleteFailureBadChallenge         CompleteFailure = "bad-challenge"
	CompleteFailureKeyMismatch          CompleteFailure = "key-mismatch"
	CompleteFailureBadHandoff           CompleteFailure = "bad-handoff"
	CompleteFailureReplayed             CompleteFailure = "replayed"
	CompleteFailureWalletBoundElsewhere CompleteFailure = "wallet-bound-elsewhere"
)

// CompleteFailures lists every CompleteFailure value, in declaration order.
var CompleteFailures = []CompleteFailure{
	CompleteFailureUnavailable,
	CompleteFailureNotFound,
	CompleteFailureExpired,
	CompleteFailureNotApproved,
	CompleteFailureAlreadyCompleted,
	CompleteFailureNetworkMismatch,
	CompleteFailureBadChallenge,
	CompleteFailureKeyMismatch,
	CompleteFailureBadHandoff,
	CompleteFailureReplayed,
	CompleteFailureWalletBoundElsewhere,
}

// UnlinkFailure mirrors the UnlinkFailure union in packages/types/src/cli-api.ts.
type UnlinkFailure string

const (
	UnlinkFailureUnavailable   UnlinkFailure = "unavailable"
	UnlinkFailureBadChallenge  UnlinkFailure = "bad-challenge"
	UnlinkFailureReplayed      UnlinkFailure = "replayed"
	UnlinkFailureNotLinked     UnlinkFailure = "not-linked"
	UnlinkFailurePrimaryWallet UnlinkFailure = "primary-wallet"
)

// UnlinkFailures lists every UnlinkFailure value, in declaration order.
var UnlinkFailures = []UnlinkFailure{
	UnlinkFailureUnavailable,
	UnlinkFailureBadChallenge,
	UnlinkFailureReplayed,
	UnlinkFailureNotLinked,
	UnlinkFailurePrimaryWallet,
}

// CliLinkFailure mirrors the CliLinkFailure union in packages/types/src/cli-api.ts.
type CliLinkFailure string

const (
	CliLinkFailureNetworkMismatch CliLinkFailure = "network-mismatch"
	CliLinkFailureBadChallenge    CliLinkFailure = "bad-challenge"
	CliLinkFailureUnavailable     CliLinkFailure = "unavailable"
)

// CliLinkFailures lists every CliLinkFailure value, in declaration order.
var CliLinkFailures = []CliLinkFailure{
	CliLinkFailureNetworkMismatch,
	CliLinkFailureBadChallenge,
	CliLinkFailureUnavailable,
}

// CliFailureCode mirrors the CliFailureCode union in packages/types/src/cli-api.ts.
type CliFailureCode string

const (
	CliFailureCodeBadRequest           CliFailureCode = "bad-request"
	CliFailureCodeRateLimited          CliFailureCode = "rate-limited"
	CliFailureCodeCrossOrigin          CliFailureCode = "cross-origin"
	CliFailureCodeNotSignedIn          CliFailureCode = "not-signed-in"
	CliFailureCodeInvalidPublicKey     CliFailureCode = "invalid-public-key"
	CliFailureCodeUnknownNetwork       CliFailureCode = "unknown-network"
	CliFailureCodeNetworkMismatch      CliFailureCode = "network-mismatch"
	CliFailureCodeUnavailable          CliFailureCode = "unavailable"
	CliFailureCodeNotFound             CliFailureCode = "not-found"
	CliFailureCodeExpired              CliFailureCode = "expired"
	CliFailureCodeAlreadyUsed          CliFailureCode = "already-used"
	CliFailureCodeNoProfile            CliFailureCode = "no-profile"
	CliFailureCodeNoKey                CliFailureCode = "no-key"
	CliFailureCodeNotApproved          CliFailureCode = "not-approved"
	CliFailureCodeAlreadyCompleted     CliFailureCode = "already-completed"
	CliFailureCodeBadChallenge         CliFailureCode = "bad-challenge"
	CliFailureCodeKeyMismatch          CliFailureCode = "key-mismatch"
	CliFailureCodeBadHandoff           CliFailureCode = "bad-handoff"
	CliFailureCodeReplayed             CliFailureCode = "replayed"
	CliFailureCodeWalletBoundElsewhere CliFailureCode = "wallet-bound-elsewhere"
	CliFailureCodeNotLinked            CliFailureCode = "not-linked"
	CliFailureCodePrimaryWallet        CliFailureCode = "primary-wallet"
)

// CliFailureCodes lists every CliFailureCode value, in declaration order.
var CliFailureCodes = []CliFailureCode{
	CliFailureCodeBadRequest,
	CliFailureCodeRateLimited,
	CliFailureCodeCrossOrigin,
	CliFailureCodeNotSignedIn,
	CliFailureCodeInvalidPublicKey,
	CliFailureCodeUnknownNetwork,
	CliFailureCodeNetworkMismatch,
	CliFailureCodeUnavailable,
	CliFailureCodeNotFound,
	CliFailureCodeExpired,
	CliFailureCodeAlreadyUsed,
	CliFailureCodeNoProfile,
	CliFailureCodeNoKey,
	CliFailureCodeNotApproved,
	CliFailureCodeAlreadyCompleted,
	CliFailureCodeBadChallenge,
	CliFailureCodeKeyMismatch,
	CliFailureCodeBadHandoff,
	CliFailureCodeReplayed,
	CliFailureCodeWalletBoundElsewhere,
	CliFailureCodeNotLinked,
	CliFailureCodePrimaryWallet,
}

// PollStatus mirrors the PollStatus union in packages/types/src/cli-api.ts.
type PollStatus string

const (
	PollStatusPending   PollStatus = "pending"
	PollStatusApproved  PollStatus = "approved"
	PollStatusRejected  PollStatus = "rejected"
	PollStatusCompleted PollStatus = "completed"
	PollStatusExpired   PollStatus = "expired"
)

// PollStatuses lists every PollStatus value, in declaration order.
var PollStatuses = []PollStatus{
	PollStatusPending,
	PollStatusApproved,
	PollStatusRejected,
	PollStatusCompleted,
	PollStatusExpired,
}

// ErrorBody mirrors the ErrorBody interface in packages/types/src/cli-api.ts.
type ErrorBody struct {
	Error string         `json:"error"`
	Code  CliFailureCode `json:"code"`
}

// PairStartRequest mirrors the PairStartRequest interface in packages/types/src/cli-api.ts.
type PairStartRequest struct {
	Network   string `json:"network"`
	PublicKey string `json:"publicKey,omitempty"`
}

// PairStartResponse mirrors the PairStartResponse interface in packages/types/src/cli-api.ts.
type PairStartResponse struct {
	State     string `json:"state"`
	PollToken string `json:"pollToken"`
	UserCode  string `json:"userCode"`
	ExpiresAt string `json:"expiresAt"`
}

// PairStatusResponse mirrors the PairStatusResponse interface in packages/types/src/cli-api.ts.
type PairStatusResponse struct {
	Status PollStatus `json:"status"`
}

// PairApproveRequest mirrors the PairApproveRequest interface in packages/types/src/cli-api.ts.
type PairApproveRequest struct {
	State string `json:"state"`
}

// PairApproveResponse mirrors the PairApproveResponse interface in packages/types/src/cli-api.ts.
type PairApproveResponse struct {
	OK          bool   `json:"ok"`
	HandoffCode string `json:"handoffCode"`
}

// PairRejectRequest mirrors the PairRejectRequest interface in packages/types/src/cli-api.ts.
type PairRejectRequest struct {
	State string `json:"state"`
}

// PairRejectResponse mirrors the PairRejectResponse interface in packages/types/src/cli-api.ts.
type PairRejectResponse struct {
	OK bool `json:"ok"`
}

// PairCompleteRequest mirrors the PairCompleteRequest interface in packages/types/src/cli-api.ts.
type PairCompleteRequest struct {
	State       string `json:"state"`
	Transaction string `json:"transaction"`
	HandoffCode string `json:"handoffCode,omitempty"`
}

// PairCompleteResponse mirrors the PairCompleteResponse interface in packages/types/src/cli-api.ts.
type PairCompleteResponse struct {
	OK              bool   `json:"ok"`
	Wallet          string `json:"wallet"`
	Handle          string `json:"handle"`
	IndexingPending bool   `json:"indexingPending"`
}

// UnlinkRequest mirrors the UnlinkRequest interface in packages/types/src/cli-api.ts.
type UnlinkRequest struct {
	Transaction string `json:"transaction"`
}

// UnlinkResponse mirrors the UnlinkResponse interface in packages/types/src/cli-api.ts.
type UnlinkResponse struct {
	OK     bool   `json:"ok"`
	Wallet string `json:"wallet"`
	Handle string `json:"handle"`
}

// WhoamiResponse mirrors the WhoamiResponse interface in packages/types/src/cli-api.ts.
type WhoamiResponse struct {
	PublicKey string `json:"publicKey"`
	Handle    string `json:"handle"`
	Linked    bool   `json:"linked"`
	Network   string `json:"network"`
}

// ChallengeResponse mirrors the ChallengeResponse interface in packages/types/src/cli-api.ts.
type ChallengeResponse struct {
	Transaction       string `json:"transaction"`
	NetworkPassphrase string `json:"network_passphrase"`
}

// CliLinkVerifyRequest mirrors the CliLinkVerifyRequest interface in packages/types/src/cli-api.ts.
type CliLinkVerifyRequest struct {
	Transaction string `json:"transaction"`
}

// CliLinkVerifyResponse mirrors the CliLinkVerifyResponse interface in packages/types/src/cli-api.ts.
type CliLinkVerifyResponse struct {
	Verified  bool   `json:"verified"`
	PublicKey string `json:"publicKey"`
}
